### ISSUE TITLE
データベース設計

### ISSUE THREAD

**Issue by udaikue** [udaikue/myground#2]
### 初版
![MyGround drawio](https://user-images.githubusercontent.com/58643754/136676887-0c980b07-1e67-4081-81b2-28bc7d6b379c.png)

### 解説 & 気になるところ
- モデル名が適切か
- diariesとnews(linkの集まり)は、Twitterの設計で言うとユーザーといいねの関係と同じかと思い参考にしました
- scoresは、gamesの項目が多くなってしまうので1回~9回の得点だけを入れるために作りました

### 修正版
![MyGround drawio](https://user-images.githubusercontent.com/58643754/138849137-8552755e-6137-4fce-bee1-45698c3c53a8.png)

**Comment by komagata** [comment]
@udaikue レビューして下記に書いていっちゃいますね〜

gameテーブルのgame_idやgame_categoryなど、テーブル名と重複してるものは「頭痛が痛い」のように冗長なのでid, categoryなどがいいと思います。

scoreのhome1, 2, 3...やvisitor1, 2, 3...が何を示すかちょっとわからなかったんですが、これってどういうものですかね？

**Comment by komagata** [comment]
@udaikue カラム名から内容が想像できる名前がいいですね。home、visitorだと何が入るのかちょっとわからないかもです。

**Comment by udaikue** [comment]
@komagata team_homeとteam_visitorに変えました。

![スクリーンショット 2021-10-20 22 17 46](https://user-images.githubusercontent.com/58643754/138100621-fe3ab474-8943-48c8-96f0-0910ddec458a.png)

**Comment by udaikue** [comment]
【追記】
ちょっと変更しました。

- データを取得するサイトがオープン戦などに対応していなかったためGameのcategoryを削除
- TeamとGameにleague_idを追加


2つめは試合日程を表示させるときに、できたら登録した好きなチームを上位に表示したいので、そのために追加しました。

**Comment by komagata** [comment]
@udaikue 確認しました、OKですー🙆‍♂️

**Comment by udaikue** [comment]
@komagata ありがとうございます〜🙌
